### PR TITLE
Add diff tests for `renameCollection` command

### PR DESCRIPTION
**Pull request by rumyantseva**
Closes FerretDB/FerretDB#1517.
The implementation is FerretDB/FerretDB#2343.

### CODE REVIEW

**Review by AlekSi — COMMENTED** [review]
Please update PR description and fix linters

**Comment by rumyantseva** [comment]
@AlekSi what should be in the description?

**Review by w84thesun — DISMISSED** [review]
LGTM!

**Review by noisersup — APPROVED** [review]

**Review by chilagrow — DISMISSED** [review]

**Review by AlekSi — CHANGES_REQUESTED** [review]
Tests fail

**Comment by noisersup** [comment]
Is this one ready for review? I see that there are similar error messages like previously

**Review by noisersup — APPROVED** [review]
:shipit:

**Review by b1ron — APPROVED** [review]

**Pull request merged**
