### PR TITLE
Add diff for `findandmodify` dollar prefixed field name

### PR DESCRIPTION
**Pull request by chilagrow**
See https://github.com/FerretDB/FerretDB/issues/2736 and https://github.com/FerretDB/FerretDB/pull/2785.

This PR will create diff after https://github.com/FerretDB/FerretDB/pull/2727. So merge this after https://github.com/FerretDB/FerretDB/pull/2727 is merged.

### CODE REVIEW

**Comment by AlekSi** [comment]
FerretDB/FerretDB#2727 is merged, so marking it as ready for review. We should restart CI jobs in an hour or so, after their a new Docker image

**Review by AlekSi — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
LGTM

**Review by b1ron — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]

**Comment by chilagrow** [comment]
Thank you for taking care of this :hugs:

**Comment by chilagrow** [comment]
I see that dance already has mongodb 6.0.6 https://github.com/FerretDB/dance/blob/main/build/deps/mongo6.Dockerfile
I think that's why this PR passed CI. so all is good!

**Pull request merged**
