### PR TITLE
Add an ignore category for tests

### LINKED ISSUE #177: Add a new category of tests: unstable
Unstable tests may pass, fail or be skipped. They should not be counted against stats (and there should not be fields for unstable tests in `Stats` struct).

### PR DESCRIPTION
**Pull request by b1ron**
Closes #177.

### CODE REVIEW

**Review by AlekSi — APPROVED** [review]
LGTM overall, but please fix linters

**Comment by b1ron** [comment]
I renamed the new field to `ignore` for clarity.

**Review by AlekSi — APPROVED** [review]

**Comment by b1ron** [comment]
Once this is merged #311 can be done.

**Review by noisersup — APPROVED** [review]
Cool!

**Pull request merged**
