### PR TITLE
Use Dependabot to manage Docker Compose deps

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Review by seeforschauer — APPROVED** [review]

**Comment by seeforschauer** [comment]
@AlekSi dance test failed.

**Review by seeforschauer — CHANGES_REQUESTED** [review]
dance tests failed.

**Comment by noisersup** [comment]
Sorry if I invoked automerge by accident. Just wanted to say that I'm not sure how provided changes could break dance tests.

**Comment by AlekSi** [comment]
No, it was me who merged that manually :) Auto-merge does not work when CI fails. But that change does not affect CI, so I went ahead and merged it. I guess the CI failure will be resolved in your PR for `common`

**Comment by noisersup** [comment]
should I just mark `go.mongodb.org/mongo-driver/examples/documentation_examples/TestDocumentationExamples` tests as a fail for mongodb?

**Comment by AlekSi** [comment]
I would say spend like 10 minutes top to investigate why they started to fail. Are they fluky? Then let's mark them, yeah

**Pull request merged**
